[13.0][FIX] datamodel: Error when NestedModel inside other field (Example: field.List())
OCA/rest-framework pull request #159
Opened 2021-05-20 12:02 UTC by CarlosRoca13

Before this patch, when we had a NestedModel inside a field.List the datamodel could not be constructed because the List object hasn't the variable _env.

Now we get the absolute parent to avoid this error and allow to make list of NestedModels.

Capture before the patch:
![image](https://user-images.githubusercontent.com/35952655/118975013-cad0ef00-b973-11eb-97f4-7c07c5d5ab11.png)

Capture after the patch:
![image](https://user-images.githubusercontent.com/35952655/118975196-0966a980-b974-11eb-8151-c2e6178f1c94.png)

cc @Tecnativa TT27860

2021-05-20 12:12 UTC, CarlosRoca13 commented
Please @lmignon, can you check it?

2021-06-27 21:49 UTC, fd-oncodna commented
While I do agree that it is a bug and it should be fixed, nesting multiple objects should not be achieved by combining a `NestedModel` within a `List` field, but rather by declaring the nested model as `many=True` (`images = NestedModel('my.image.model', many=True)`)

2021-06-30 13:39 UTC, lmignon commented on datamodel/fields.py
> +                if "parent" not in dir(parent):
if not hasattr(parent, "parent"):

2021-06-30 13:42 UTC, lmignon requested changes
Thank you @CarlosRoca13.
A little comment and can you split your changes into 2 commits? 1 for the fix and another one for the new readme. 

Regards

2021-07-12 06:31 UTC, CarlosRoca13 commented
@lmignon changes done!

2021-07-12 06:37 UTC, lmignon requested changes

2021-07-12 06:37 UTC, lmignon commented on datamodel/static/description/index.html
> +<<<<<<< HEAD
Remaining conflict info lines

2021-07-12 06:40 UTC, lmignon commented
@CarlosRoca13 Take care of the @fd-oncodna advice when you design your API!
Moreover, can you add a testcase for your fix PLZ

regards.

2021-07-12 07:34 UTC, CarlosRoca13 commented
@lmignon @fd-oncodna Thanks, I will keep it on mind :)

Changes done!

2021-07-23 08:53 UTC, lmignon approved these changes
Thank you @CarlosRoca13 LGTM!

2021-08-25 07:08 UTC, pedrobaeza commented
Can this be merged?

2021-08-25 07:20 UTC, lmignon commented
/ocabot merge patch

2021-08-25 07:21 UTC, pedrobaeza commented
Thanks!

2021-08-25 07:32 UTC, merged