[FIX] base_rest_datamodel: remove incorrect validation of responses
OCA/rest-framework pull request #169
Opened 2021-06-20 11:06 UTC by fdegrave

In marshmallow, `dump` (serialization) and `load` (deserialization) operations using the same schema are not symmetrical in general. That is because fields can be declared as `dump_only` or `load_only`. That means that if you try to `load` data you just `dumped` it could fail, and vice-versa.

And that is exactly what is (was) wrong with this validation: the `validate` method on the `ModelClass` uses `load` to validate the data. That means that if you declare some fields to be `dump_only`, this validation necessarily crashes.

Moreover, it seems that this validation is not only incorrect but also useless (if it worked as intended), since it bases its verification on the very same schema as the one that was just used to serialize the data.

2021-06-30 15:05 UTC, lmignon commented
@fdegrave  Validation is IMO a requirement  since I want to be sure that the data returned by the service are conform to the schema. I understand that the current one is not right but how can we provide such a validation.?

2021-06-30 19:40 UTC, fdegrave commented
The simple fact that the schema is used to dump the data **is already a validation**. Here is a simple example:

```python
from marshmallow import Schema, fields


class MySchema(Schema):
    my_string = fields.Str(required=True)
    my_integer = fields.Integer()
    

class DataClass:
    def __init__(self, my_string, my_integer):
        self.my_string = my_string
        self.my_integer = my_integer
```

Now let's dump a valid instance:

```
>>> instance_ok = DataClass(my_string="Yes", my_integer=5)
>>> MySchema().dump(instance_ok)
{'my_string': 'Yes', 'my_integer': 5}
```
As expected. Now let's do it with an instance that **does not conform** to the schema:

```
>>> instance_bad = DataClass(my_string=1, my_integer="No")
>>> MySchema().dump(instance_bad)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fd/.virtualenvs/odoo/lib/python3.8/site-packages/marshmallow/schema.py", line 547, in dump
    result = self._serialize(processed_obj, many=many)
  File "/home/fd/.virtualenvs/odoo/lib/python3.8/site-packages/marshmallow/schema.py", line 515, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/home/fd/.virtualenvs/odoo/lib/python3.8/site-packages/marshmallow/fields.py", line 318, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/home/fd/.virtualenvs/odoo/lib/python3.8/site-packages/marshmallow/fields.py", line 898, in _serialize
    ret = self._format_num(value)  # type: _T
  File "/home/fd/.virtualenvs/odoo/lib/python3.8/site-packages/marshmallow/fields.py", line 873, in _format_num
    return self.num_type(value)
ValueError: invalid literal for int() with base 10: 'No'
```

As you can see, **validation is included** in the `dump` method, since the schema is used during the serialization. No need to try to re-validate it afterwards.

2021-06-30 19:53 UTC, fdegrave commented
However you are right that not everything is validated (see [there](https://github.com/marshmallow-code/marshmallow/issues/682#issuecomment-332758061) for example). In the same thread, people have the exact same issue we are discussing here ([link](https://github.com/marshmallow-code/marshmallow/issues/682#issuecomment-580153238)) but don't come with a solution... 

One thing that we *could* do is list the names of `dump_only` fields, and pass them to the `validate` method under the `partial` parameter (which can be a list of field names).

I'll try that tomorrow.

2021-06-30 20:06 UTC, fdegrave commented
What they do [there](https://github.com/globality-corp/microcosm-pubsub/pull/233) is instantiating the schema with a `unknown=EXCLUDE` parameter.

Therefore a second solution would be to add  a new `unknown` parameter to `validate` (define in `marshmallow_objects`) and override it to modify the way the schema is instantiated. Here is the current method:

```python
    @classmethod
    def validate(cls, data, context=None, many=None, partial=None):
        schema = cls.__get_schema_class__(context=context, partial=partial)
        return schema.validate(data, many=many, partial=partial)
```
And we could simply do:

```python
    @classmethod
    def validate(cls, data, context=None, many=None, partial=None, unknown=None):
        schema = cls.__get_schema_class__(context=context, partial=partial, unknown=unknown)
        return schema.validate(data, many=many, partial=partial)
```

And modify the current validation with:

```python
from marshmallow import EXCLUDE

...

errors = ModelClass.validate(json, many=self._is_list, unknown=EXCLUDE)
```

2021-07-01 10:47 UTC, fdegrave commented
I implemented my latest proposition, but it was trickier than I though because of nested models (no control on the schema for those, no way to easily override them during validation -- had to be creative, I think it's the cleanest I can do).

2021-07-01 12:55 UTC, fdegrave commented
I rebased my branch after the fix of the tests have been merged. Hopefully everything should work OK.

2021-07-01 17:30 UTC, fdegrave commented
Nearly there :-D

2021-07-01 22:06 UTC, fdegrave commented
Victory!

2021-07-23 08:49 UTC, lmignon requested changes
@fdegrave Thank you for this fix and all your experiments to provide the right one. First of all, feel free to add your name into the list of contributors!
Before merging I propose to add some tests and change the existing one (see my comments)

2021-07-23 08:49 UTC, lmignon commented on datamodel/core.py
> +        with ExitStack() as stack:
:heart:

2021-07-23 08:49 UTC, lmignon commented on base_rest_demo/tests/test_new_api.py
> +    def test_01(self):
Your test should not be an HttpCase test. Its possible to test the `restapi.Datamodel`class alone...
For ex:
```python
import mock
from odoo.addons.datamode import fields
from odoo.addons.datamode.core import Datamodel
from odoo.addons.datamodel.tests import common
from odoo.addons.base_rest_data_model import restapi



class TestDataModel(common.DatamodelRegistryCase):

    def test_to_response_exclude(self):
        class MyModel(DataModel):
            _name = "my.model"
            ....

        MyModel._build_datamodel(self.datamodel_registry)

        restapi_datamodel = restapi.Datamodel("my.model")
        mock_service = mock.Mock()
        mock.env.datamodels = self.datamodel_registry

        my_model = MyModel()
        res = restapi_datamodel.to_response(mock_service, my_model)
        ...
```
This test can be therefore put into the base_rest_datamodel addon.

2021-07-23 08:49 UTC, lmignon commented on datamodel/core.py
> +    def validate(cls, data, context=None, many=None, partial=None, unknown=None):
Can you add a dedicated tests to chack that the unknow param is recursively applied to nested schemas on validate and cleaned up after

2021-07-28 14:55 UTC, lmignon commented on base_rest_datamodel/tests/test_response.py
> +@odoo.tests.common.post_install(True)
These 2 lines should be removed. Test must be run at install

2021-07-29 06:36 UTC, lmignon approved these changes

2021-09-12 20:15 UTC, fdegrave commented
Is there anything still preventing the merge?

2021-10-08 06:39 UTC, lmignon commented
/ocabot merge patch

2021-10-08 06:40 UTC, lmignon commented
times to merge a pending merge for a long time

2021-10-08 07:04 UTC, merged