[16.0][MIG] - rest_log
OCA/rest-framework pull request #354
Opened 2023-06-26 07:21 UTC by sbejaoui

2023-06-26 11:09 UTC, lmignon approved these changes

2023-06-26 11:11 UTC, lmignon commented
@sbejaoui Can you prepare a PR base on this one with the improvements listed below:
* https://github.com/acsone/rest-framework/commit/d542d31d7c60950a32c272d9612253f3c887481a
* https://github.com/acsone/rest-framework/commit/3f84ffa477116f4aae7d95628c6e8a536d03d4bb
* https://github.com/acsone/rest-framework/commit/1f750a4c63ade66a0ee78779d533db8532ba3cd4
* https://github.com/acsone/rest-framework/commit/35f06b977d5aa71edbb1a1f1db2f530f4308567c
* https://github.com/acsone/rest-framework/commit/1032dfdf3eb4442e5d39fb7ae8efe050b5fdbea1

2023-06-27 06:25 UTC, lmignon approved these changes
LGTM (Code review)

2023-07-11 09:33 UTC, lmignon commented
/ocabot merge nobump

2023-07-19 13:43 UTC, sbidoul commented
We need to finish #360 to get the 16.0 branch green again.

2023-07-20 06:36 UTC, simahawk requested changes
I see some fixes: can you please check v14?
AFAIR we made some fix/imp there (the Response obj for instance).

2023-07-20 06:36 UTC, simahawk commented on test-requirements.txt
> +mock
mock is not required, pls import it from unittest

2023-07-20 06:49 UTC, lmignon commented
> 

@sbejaoui Can you include:
* 7b3e019a31ef620f3433a75dc47b8af8df5c4e26
* 41ff3aeac023e899bd5778728f87826f9e69ec62
* 6db08371025d449337b9621ee6aed75b8518e877
* 5d6ee6d42b698bb681ac0409a4136261b7e7eba1
* 89ae7cc8febf1ad01c994fa7801f723f6cdd732c
* cecf2b178c28b0ae2d29fc0b3e0ae46bacc7b9d6

2023-12-12 08:46 UTC, lmignon commented
/ocabot merge patch

2023-12-12 08:56 UTC, merged