[FIX] fastapi: allow test with no authenticated partner
OCA/rest-framework pull request #373
Opened 2023-09-11 13:00 UTC by matthieusaison

In case you need an anonymous call in your test.
The /fastapi/tests/common.py  _create_test_client() function fails due to an empty authenticated_partner_impl.

This proposal allows you to define an empty partner for your test:
 `cls.default_fastapi_authenticated_partner = cls.env["res.partner"]`
 
An authenticated test can be done like this: 
`self._create_test_client(partner=self.test_partner)`

2023-09-21 13:09 UTC, sebastienbeau commented
LGTM (code review), @lmignon ok for you ?

2023-09-21 13:09 UTC, sebastienbeau approved these changes

2023-09-21 13:25 UTC, lmignon requested changes
The only change to do is: 

```python

partner = partner or self.default_fastapi_authenticated_partner or self.env["res.partner"]
dependencies[authenticated_partner_impl] = partial(lambda a: a, partner)


```

2023-09-22 06:10 UTC, lmignon commented
ping @matthieusaison

2023-09-25 07:54 UTC, matthieusaison commented
Thanks @lmignon for your feedback, the change is made.

2023-09-25 09:10 UTC, lmignon approved these changes
Code review

2023-09-25 09:11 UTC, sebastienbeau commented
/ocabot merge patch

2023-09-25 09:14 UTC, merged