[18.0][MIG] fastapi: Migration to 18.0
OCA/rest-framework pull request #471
Opened 2024-11-08 20:05 UTC by cormaza

Change serialization error class to test retry failure

2024-11-19 12:42 UTC, marielejeune commented
Hi @cormaza, thanks for the work. Do you have any idea for the last fail in the tests?

2024-11-19 16:44 UTC, cormaza commented
> Hi @cormaza, thanks for the work. Do you have any idea on how to fix the tests?

I'm not pretty sure, because if you can see test log, It seems every test works fine, but because log has an error text can't be processed as passed by CI, I think can be the parser version now aggregate another validation, maybe in older versions doesn't matter, We can ask to @pedrobaeza? WDYT?

![image](https://github.com/user-attachments/assets/3fd1e092-f24f-427a-9cbf-33ef7cab8676)

2024-11-19 16:47 UTC, pedrobaeza commented
I don't know about this repository. @lmignon may say.

2024-11-19 16:51 UTC, marielejeune approved these changes
LGTM (Code + Functional review)

2024-11-19 17:24 UTC, lmignon commented
@cormaza the commit https://github.com/OCA/rest-framework/pull/476/commits/4dd16b2f6ab4d9d09f19b56a6ee201a372e435e2 should solve this issue.

2024-11-19 18:16 UTC, cormaza commented
> @cormaza the commit [4dd16b2](https://github.com/OCA/rest-framework/commit/4dd16b2f6ab4d9d09f19b56a6ee201a372e435e2) should solve this issue.

Thank you, but doesn't work

2024-11-19 21:20 UTC, cormaza commented
@lmignon I added in other test method, and now works, thank you for help

2024-11-20 07:15 UTC, lmignon requested changes

2024-11-20 07:15 UTC, lmignon commented on fastapi/tests/test_fastapi_demo.py
> +    @mute_logger("odoo.addons.fastapi.tests.common")
The mute logger must be removed here

2024-11-20 14:59 UTC, cormaza commented on fastapi/tests/test_fastapi_demo.py
> +    @mute_logger("odoo.addons.fastapi.tests.common")
done!

2025-01-30 13:15 UTC, lmignon commented
/ocabot migration fastapi

2025-01-30 13:24 UTC, lmignon reviewed
LGTM (waiting for the merge of the `endpoint_route_handler` addon)

2025-01-30 13:25 UTC, lmignon approved these changes

2025-02-01 18:39 UTC, dnplkndll approved these changes
tested with demo api

2025-02-03 08:09 UTC, lmignon commented
/ocabot merge nobump

2025-02-03 08:13 UTC, merged